### ISSUE TITLE
Completely broken on 1.572

### ISSUE THREAD

**Issue by TheReverend403** [Dakota628/jenkins-clean-theme#11]
Theme is now broken due to the changes in 1.572: 
http://jenkins-ci.org/changelog
https://github.com/jenkinsci/jenkins/pull/1310

**Comment by MosheZada** [comment]
+1

**Comment by Dakota628** [comment]
fixed in 7a2950a

**Comment by schlamar** [comment]
Not really:

![jenkins](https://cloud.githubusercontent.com/assets/238652/9222896/b8e68068-40f5-11e5-96e5-38110a04b9fe.PNG)

**Comment by schlamar** [comment]
Ah sorry I put the files in the wrong location, it's working now :)
