### ISSUE TITLE
Jenkins head is there

### ISSUE THREAD

**Issue by Yumash** [Dakota628/jenkins-clean-theme#13]
Hi guys! That's a perfect theme, but it seems that Jenkins head not disappearing 
![2014-12-08 12 38 39](https://cloud.githubusercontent.com/assets/6568685/5337226/2b2547a4-7ed7-11e4-9ab4-8ad0fbe2ea3e.png)

Safari 8, Jenkins ver. 1.593

**Comment by agherzan** [comment]
Jenkins ver. 1.602
Black bar still here and some elements are very bad rendered.

**Comment by Dakota628** [comment]
fixed in 7a2950a
