### ISSUE TITLE
There are appears just two symbols of agents names

### ISSUE THREAD

**Issue by yolcatl** [Dakota628/jenkins-clean-theme#21]
![3995a-clip-6kb](https://cloud.githubusercontent.com/assets/8822784/9032791/e0cdafa2-39ca-11e5-8e8f-001ac9caf5b5.png)
![iss2](https://cloud.githubusercontent.com/assets/8822784/9032861/80b8bfe8-39cb-11e5-845d-d49ab9e67cde.png)

Thanks!

**Comment by RX14** [comment]
Can confirm, happens here: http://ci.novaapi.net/
