### ISSUE TITLE
 Bottom bar appears on middle of page

### ISSUE THREAD

**Issue by yolcatl** [Dakota628/jenkins-clean-theme#22]
In jobs with long build history bottom status bar appears like this:
![ac38d-clip-39kb](https://cloud.githubusercontent.com/assets/8822784/9120826/39d81f24-3c87-11e5-8dd1-4a1142c55cfa.png)

**Comment by wavded** [comment]
I also am experiencing this issue.  Seems to happen on any page that is longer.

**Comment by bsideup** [comment]
+1

**Comment by Dakota628** [comment]
Should have been fixed by PR 23.
