### ISSUE TITLE
Create Github Page

### ISSUE THREAD

**Issue by leopoiroux** [Dakota628/jenkins-clean-theme#8]
Hi,
Can you create a "Github Page" ?
(example : https://github.com/spotlab/jenkins-clean-theme/tree/gh-pages)

The "raw" url is blocked by Github :(

**Comment by o5** [comment]
You can use some services like https://rawgit.com/
```
https://cdn.rawgit.com/Dakota628/jenkins-clean-theme/master/master.css
https://cdn.rawgit.com/Dakota628/jenkins-clean-theme/master/master.js
```

**Comment by leopoiroux** [comment]
Thks for the link. Good idea.
